// Generated from the reviewed v0.2 design. World remains outside this release.
namespace ArcanaDuel {
public static class CardCatalog {
 public static CardRule[] Create(){return new CardRule[]{
  new CardRule{Arcana=0,Rank=0,Name=@"第一步",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。",Reversed=@"抽 1 张牌。然后可主动弃 1 张手牌，获得两种不同的小阿尔卡纳各 1 个。"},
  new CardRule{Arcana=0,Rank=1,Name=@"轻装远行",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。然后可将自己的最多 2 个小阿尔卡纳，逐个变为其他任意种类，总数不变。",Reversed=@"抽 1 张牌，获得两种不同的小阿尔卡纳各 1 个。"},
  new CardRule{Arcana=0,Rank=2,Name=@"零之可能",Cost=3,Payment=@"any",Upright=@"造成 3 点伤害。可额外消耗任意 1 个小阿尔卡纳，使伤害 +1。",Reversed=@"抽 2 张牌，获得两种不同的小阿尔卡纳各 1 个。"},
  new CardRule{Arcana=1,Rank=0,Name=@"点火",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害，获得 1 权杖。",Reversed=@"获得 2 权杖。"},
  new CardRule{Arcana=1,Rank=1,Name=@"巧手戏法",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。若本回合此前打出过其他牌，可额外消耗 1 权杖，使伤害 +1。",Reversed=@"恢复 1 费用，抽 1 张牌。可额外消耗 1 权杖，使抽牌数量 +1。"},
  new CardRule{Arcana=1,Rank=2,Name=@"万象之手",Cost=2,Payment=@"crystal",Upright=@"可额外消耗至多 2 权杖；造成 2 点伤害，每消耗 1 权杖，伤害 +1。",Reversed=@"将你的回合费用补满至 3，然后抽 1 张牌。"},
  new CardRule{Arcana=2,Rank=0,Name=@"帷幕一瞥",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害，预知 1。",Reversed=@"预知 2，然后抽 1 张牌。"},
  new CardRule{Arcana=2,Rank=1,Name=@"银月之书",Cost=2,Payment=@"mana",Upright=@"展示牌库顶 1 张：若是 C，造成 3 点伤害；否则造成 2 点。展示牌放回原位。",Reversed=@"预知 2，抽 1 张牌，获得 1 圣杯。"},
  new CardRule{Arcana=2,Rank=2,Name=@"隐秘启示",Cost=3,Payment=@"any",Upright=@"造成 3 点伤害。若本回合此前使用过预知，伤害 +1；满足该条件时还可额外消耗 1 圣杯，再使伤害 +1。",Reversed=@"预知 4，抽 2 张牌，获得 1 圣杯。"},
  new CardRule{Arcana=3,Rank=0,Name=@"萌芽",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害，获得 1 圣杯。",Reversed=@"获得 1 权杖和 1 圣杯。"},
  new CardRule{Arcana=3,Rank=1,Name=@"丰饶庭园",Cost=2,Payment=@"mana",Upright=@"获得 2 屏障和 2 权杖。",Reversed=@"抽 1 张牌，获得 2 圣杯。"},
  new CardRule{Arcana=3,Rank=2,Name=@"母神丰收",Cost=3,Payment=@"any",Upright=@"造成 3 点伤害。可额外消耗 2 权杖和 2 圣杯，使伤害 +3。",Reversed=@"抽 2 张牌，获得 2 权杖和 1 圣杯。"},
  new CardRule{Arcana=4,Rank=0,Name=@"王令",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。若结算前已占优，获得 1 星币。",Reversed=@"获得 1 屏障和 1 星币。"},
  new CardRule{Arcana=4,Rank=1,Name=@"铁律疆界",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害。若结算前已占优，获得 1 星币。",Reversed=@"获得 4 星币。"},
  new CardRule{Arcana=4,Rank=2,Name=@"不动王座",Cost=3,Payment=@"crystal",Upright=@"可额外消耗至多 2 星币；造成 3 点伤害，每消耗 1 星币，伤害 +1。",Reversed=@"获得 3 屏障，抽 1 张牌，获得 1 星币。"},
  new CardRule{Arcana=5,Rank=0,Name=@"诵经",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。若本回合此前打出过教皇牌，获得 1 星币。",Reversed=@"抽 1 张牌。若本回合此前打出过教皇牌，获得 1 星币。"},
  new CardRule{Arcana=5,Rank=1,Name=@"传承",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。若本回合此前打出过教皇牌，伤害 +1。",Reversed=@"回收 1 张教皇 A 或 B，获得 2 星币。"},
  new CardRule{Arcana=5,Rank=2,Name=@"三重圣仪",Cost=2,Payment=@"crystal",Upright=@"造成 3 点伤害。若本回合此前分别打出过教皇 A 和教皇 B，可额外消耗 2 星币，使伤害 +2。",Reversed=@"分别回收至多 1 张教皇 A、1 张教皇 B，获得 1 星币。"},
  new CardRule{Arcana=6,Rank=0,Name=@"相遇",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。若本回合上一张打出的牌来自其他大阿尔卡纳，获得 1 权杖。",Reversed=@"抽 1 张牌。若本回合上一张打出的牌来自其他大阿尔卡纳，获得 1 圣杯。"},
  new CardRule{Arcana=6,Rank=1,Name=@"交织",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害。若本回合此前打出过至少两种大阿尔卡纳的牌，伤害 +1。",Reversed=@"获得 1 权杖和 1 圣杯，抽 1 张牌。然后可将 1 张手牌放到牌库底；如此做，再抽 1 张牌。"},
  new CardRule{Arcana=6,Rank=2,Name=@"命运共鸣",Cost=3,Payment=@"any",Upright=@"造成 3 点伤害。若本回合此前打出过至少两种大阿尔卡纳的牌，伤害 +1；满足该条件时还可额外消耗 1 权杖、1 圣杯，再使伤害 +2。",Reversed=@"回收两张来自不同大阿尔卡纳的 A 或 B，获得任意 1 个小阿尔卡纳。可用目标不足两张时，只回收可用目标。"},
  new CardRule{Arcana=7,Rank=0,Name=@"起跑",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害。若本回合此前已对对手造成过至少 1 点实际伤害，获得 1 权杖。",Reversed=@"获得 1 权杖和 1 宝剑。"},
  new CardRule{Arcana=7,Rank=1,Name=@"突阵",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。可额外消耗 1 权杖，使伤害 +1。",Reversed=@"抽 1 张牌，获得 2 权杖。"},
  new CardRule{Arcana=7,Rank=2,Name=@"凯旋冲锋",Cost=3,Payment=@"mana",Upright=@"造成 3 点伤害。若本回合此前累计实际伤害至少为 3，伤害 +1；还可额外消耗 1 宝剑，使伤害再 +1。",Reversed=@"抽 2 张牌，获得 1 权杖和 2 宝剑。"},
  new CardRule{Arcana=8,Rank=0,Name=@"狮心",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。可额外消耗 1 宝剑，使伤害 +1。",Reversed=@"获得 2 宝剑。"},
  new CardRule{Arcana=8,Rank=1,Name=@"驯服",Cost=2,Payment=@"mana",Upright=@"清除对手 1 点屏障，然后造成 2 点伤害。",Reversed=@"获得 3 宝剑和 1 屏障。"},
  new CardRule{Arcana=8,Rank=2,Name=@"温柔的暴力",Cost=3,Payment=@"any",Upright=@"可额外消耗至多 3 宝剑；造成 3 点伤害，每消耗 1 宝剑，伤害 +1。",Reversed=@"获得 4 宝剑和 2 屏障。"},
  new CardRule{Arcana=9,Rank=0,Name=@"提灯",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。若出牌离手后手牌不超过 2 张，获得 1 圣杯。",Reversed=@"抽 1 张牌。若出牌离手后原本没有手牌，改为抽 2 张。"},
  new CardRule{Arcana=9,Rank=1,Name=@"独行",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害。若出牌离手后手牌不超过 1 张，伤害 +1。",Reversed=@"查看牌库顶最多 3 张，选择其中 1 张加入手牌，其余按自定顺序放到牌库底；获得 2 圣杯。"},
  new CardRule{Arcana=9,Rank=2,Name=@"灯尽见真",Cost=2,Payment=@"crystal",Upright=@"造成 3 点伤害。若出牌离手后没有手牌，伤害 +1；还可额外消耗 1 圣杯，使伤害再 +1。",Reversed=@"抽牌直到手牌达到 4 张。"},
  new CardRule{Arcana=10,Rank=0,Name=@"一次转动",Cost=1,Payment=@"any",Upright=@"展示牌库顶 1 张：若为 C，造成 2 点伤害；否则造成 1 点。将展示牌放到牌库底。",Reversed=@"抽 1 张牌。然后可将 1 张手牌放到牌库底；如此做，获得 2 星币。"},
  new CardRule{Arcana=10,Rank=1,Name=@"潮起潮落",Cost=2,Payment=@"any",Upright=@"展示牌库顶最多 2 张。若恰有 2 张且类型不同，造成 3 点伤害；否则造成 2 点。展示牌按自定顺序放到牌库底。",Reversed=@"主动弃置最多 2 张手牌，然后抽“弃置数量 +2”张，获得 1 圣杯。"},
  new CardRule{Arcana=10,Rank=2,Name=@"命运重掷",Cost=3,Payment=@"crystal",Upright=@"可额外消耗 1 星币，先预知 3。然后二选一：①造成 3 点伤害；②展示顶最多 3 张，若 A、B、C 齐全，造成 5 点，否则造成 2 点。选②时展示牌按自定顺序放到牌库底。",Reversed=@"将自己的全部手牌按自定顺序放到牌库底，然后抽 4 张，获得 2 星币。可额外消耗 2 圣杯，将抽牌数提高到 5。"},
  new CardRule{Arcana=11,Rank=0,Name=@"天平",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害。若结算前对手的水晶比你多，伤害 +1。",Reversed=@"获得 2 星币。若结算前你的手牌比对手少，抽 1 张牌。"},
  new CardRule{Arcana=11,Rank=1,Name=@"公正之刃",Cost=2,Payment=@"mana",Upright=@"若结算前处于劣势，先清除对手 1 点屏障；然后造成 2 点伤害。",Reversed=@"获得 3 星币和 1 屏障。"},
  new CardRule{Arcana=11,Rank=2,Name=@"等价裁决",Cost=3,Payment=@"any",Upright=@"造成 3 点伤害。若结算前对手的小阿尔卡纳总数至少比你多 3 个，改为造成 5 点。",Reversed=@"抽 2 张牌，获得 2 屏障。若结算前处于劣势，改为获得 3 屏障。可额外消耗 1 星币，使抽牌数量 +1。"},
  new CardRule{Arcana=12,Rank=0,Name=@"逆向凝视",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害。若结算前处于劣势，获得 1 星币。",Reversed=@"后退 1 格，然后获得 2 水晶并抽 1 张牌。"},
  new CardRule{Arcana=12,Rank=1,Name=@"自愿悬停",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。若结算前处于劣势，伤害 +1。",Reversed=@"后退 1 格，然后抽 2 张牌并获得 1 星币。最后你可以转位。"},
  new CardRule{Arcana=12,Rank=2,Name=@"献祭换位",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害。若结算前处于劣势，伤害 +2；还可额外消耗 1 星币，使伤害再 +1。",Reversed=@"后退 2 格，然后获得 3 水晶并抽 2 张牌。"},
  new CardRule{Arcana=13,Rank=0,Name=@"凋零",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。可额外主动弃 1 张手牌，使伤害 +1，并获得 1 宝剑。",Reversed=@"若有其他手牌，主动弃 1 张，然后抽 2 张；若没有其他手牌，只抽 1 张。"},
  new CardRule{Arcana=13,Rank=1,Name=@"白蔷薇",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害。若本回合此前主动弃置过手牌，伤害 +1。",Reversed=@"回收 1 张 A 或 B，获得 1 圣杯和 1 宝剑。"},
  new CardRule{Arcana=13,Rank=2,Name=@"死而复生",Cost=3,Payment=@"crystal",Upright=@"造成 3 点伤害。可额外主动弃 1 张手牌并消耗 1 宝剑，使伤害 +2。",Reversed=@"回收至多 2 张任意牌。可额外消耗 2 圣杯，将回收数量上限提高为 3 张。"},
  new CardRule{Arcana=14,Rank=0,Name=@"双杯调和",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。然后可将自己的 1 个小阿尔卡纳变为其他种类。",Reversed=@"获得两种不同的小阿尔卡纳各 1 个。"},
  new CardRule{Arcana=14,Rank=1,Name=@"等量交换",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害。可额外消耗任意 1 个小阿尔卡纳，使伤害 +1。",Reversed=@"抽 1 张牌，获得 1 水晶。然后可将自己的最多 2 个小阿尔卡纳，逐个变为其他种类，总数不变。"},
  new CardRule{Arcana=14,Rank=2,Name=@"完美比例",Cost=2,Payment=@"crystal",Upright=@"造成 2 点伤害。可额外消耗两种不同的小阿尔卡纳各 1 个，使伤害 +2。",Reversed=@"恢复 1 费用，抽 1 张牌，获得两种不同的小阿尔卡纳各 1 个。"},
  new CardRule{Arcana=15,Rank=0,Name=@"甜蜜契约",Cost=1,Payment=@"any",Upright=@"额外主动弃 1 张手牌，造成 3 点伤害。没有其他手牌时不能正位打出。",Reversed=@"获得 2 宝剑。"},
  new CardRule{Arcana=15,Rank=1,Name=@"贪欲",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。可额外消耗 1 水晶和 1 宝剑，使伤害 +2。",Reversed=@"获得 1 水晶，抽 1 张牌。可额外主动弃 1 张手牌，再获得 2 宝剑。"},
  new CardRule{Arcana=15,Rank=2,Name=@"灵魂抵押",Cost=3,Payment=@"any",Upright=@"支付固定费用后，额外消耗自己全部剩余水晶，至少 1 枚。造成“4 + 额外消耗水晶数量”点伤害，最多 7 点。没有剩余水晶不能正位打出。",Reversed=@"额外主动弃 1 张手牌；获得 2 水晶、2 宝剑，并抽 2 张牌。没有其他手牌不能逆位打出。"},
  new CardRule{Arcana=16,Rank=0,Name=@"裂痕",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害。可额外消耗 1 权杖，令对手失去 1 星币；对手没有星币时不能选择此额外消耗。",Reversed=@"获得 2 权杖。"},
  new CardRule{Arcana=16,Rank=1,Name=@"落雷",Cost=2,Payment=@"mana",Upright=@"若对手有水晶，使其失去 1 水晶并造成 1 点伤害；否则造成 2 点。可额外消耗 1 宝剑，使伤害 +1。",Reversed=@"获得 4 宝剑，清除对手 1 点屏障。"},
  new CardRule{Arcana=16,Rank=2,Name=@"巴别崩塌",Cost=3,Payment=@"mana",Upright=@"对手失去最多 3 个小阿尔卡纳，由对手选择；造成 3 点伤害，若实际失去至少 2 个，伤害 +1。",Reversed=@"双方水晶清零。按双方实际失去的水晶总数，获得等量宝剑，最多获得 3 个；然后抽 2 张牌。"},
  new CardRule{Arcana=17,Rank=0,Name=@"微光",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。若支付固定费用后没有水晶，获得 1 圣杯。",Reversed=@"获得 1 水晶和 1 圣杯。"},
  new CardRule{Arcana=17,Rank=1,Name=@"星图",Cost=2,Payment=@"mana",Upright=@"造成 2 点伤害，预知 2。",Reversed=@"抽 2 张牌，获得 1 圣杯。"},
  new CardRule{Arcana=17,Rank=2,Name=@"群星回应",Cost=3,Payment=@"crystal",Upright=@"造成 3 点伤害。若本回合此前通过卡牌效果抽过至少 2 张牌，伤害 +1；满足该条件时还可额外消耗 1 圣杯，再使伤害 +1。",Reversed=@"抽 3 张牌，获得 1 水晶和 1 圣杯。"},
  new CardRule{Arcana=18,Rank=0,Name=@"疑影",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害，然后对对手施加迷惑。",Reversed=@"抽 1 张牌，获得 1 圣杯。"},
  new CardRule{Arcana=18,Rank=1,Name=@"镜中路",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。若对手已有迷惑，伤害 +1。",Reversed=@"获得 2 屏障和 1 圣杯。然后可消耗 1 圣杯转位；允许使用本牌刚获得的圣杯。"},
  new CardRule{Arcana=18,Rank=2,Name=@"月蚀",Cost=3,Payment=@"crystal",Upright=@"造成 3 点伤害。若对手已有迷惑，伤害 +1；然后对对手施加迷惑。",Reversed=@"查看对手当前手牌，获得 2 屏障，抽 2 张牌。"},
  new CardRule{Arcana=19,Rank=0,Name=@"晨曦",Cost=1,Payment=@"mana",Upright=@"造成 1 点伤害。若本回合此前没有发生过自己的转位，获得 1 宝剑。",Reversed=@"获得 2 宝剑。"},
  new CardRule{Arcana=19,Rank=1,Name=@"烈阳",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。可额外消耗 1 宝剑，使伤害 +1。",Reversed=@"抽 1 张牌，获得 2 宝剑。"},
  new CardRule{Arcana=19,Rank=2,Name=@"正午",Cost=3,Payment=@"mana",Upright=@"清除对手 1 点屏障，然后造成 4 点伤害。",Reversed=@"抽 2 张牌，获得 2 宝剑。"},
  new CardRule{Arcana=20,Rank=0,Name=@"召声",Cost=1,Payment=@"any",Upright=@"造成 1 点伤害。若结算前弃牌区至少有 5 张牌，获得 1 宝剑。",Reversed=@"若有其他手牌，主动弃 1 张，然后抽 2 张；若没有其他手牌，只抽 1 张。"},
  new CardRule{Arcana=20,Rank=1,Name=@"旧日回音",Cost=2,Payment=@"any",Upright=@"造成 2 点伤害。若结算前弃牌区包含至少三种大阿尔卡纳，伤害 +1。",Reversed=@"回收 1 张 A 或 B，获得 1 宝剑和 1 圣杯。"},
  new CardRule{Arcana=20,Rank=2,Name=@"最终审判",Cost=3,Payment=@"crystal",Upright=@"造成 3 点伤害。若结算前弃牌区包含四种大阿尔卡纳，伤害 +1；满足该条件时还可额外消耗 1 宝剑或 1 圣杯，再使伤害 +1。",Reversed=@"回收至多两张来自不同大阿尔卡纳的 A 或 B。若结算前弃牌区包含四种大阿尔卡纳，额外获得 1 水晶。"}
 };}
}
}
